### ISSUE TITLE
Migration checklist

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-cms#58]
## Technical
- [ ] Date set for migration
- [ ] CAB raised for migration
- [ ] Existing site has a separate domain for reference (e.g. ```legacy.wmnetwork.co.uk```)
- [ ] CORS domains all correct

## Training
- [ ] Editors are trained
- [ ] Editors have done accessibility training
- [ ] Editors have an account

## Check
- [ ] Content is correct
- [ ] Integrated apps work
- [ ] Redirects work

## Emails
- [ ] Transactional emails are prepared to point to new URLs and content
- [ ] Activate transactional emails

## Post-launch
- Check inbound link errors
- Set up a place for customer services, comms and digital/data to raise issues
- Monitor traffic
